
type Game = {
	banner: string,
	capsuleimage: string,
	contentrating: string,
	description: string,
	developer: string,
	discord: string,
	executables: string,
	facebook: string,
	icon: string,
	instagram: string,
	longdescription: string,
	password: string,
	paymentaddress: string,
	productid: string,
	publisher: string,
	publisherdid: string,
	screenshots: string,
	shortdescription: string,
	status: string,
	tags: string,
	title: string,
	torrents: string,
	trailer: string,
	trailersource: string,
	twitter: string,
	version: string,
	website: string,
}

export default Game;