
export const tags = [
	'Abstract',
	'Action',
	'Action Adventure',
	'Action Roguelike',
	'Action RPG',
	'Action RTS',
	'Addictive',
	'Adventure',
	'Agriculture',
	'Aliens',
	'Alternate History',
	'Ambient',
	'America',
	'Animation & Modeling',
	'Anime',
	'Arcade',
	'Archery',
	'Arena Shooter',
	'Artificial Intelligence',
	'Assassin',
	'Asymmetric VR',
	'Asynchronous Multiplayer',
	'Atmospheric',
	'ATV',
	'Audio Production',
	'Auto Battler',
	'Automation',
	'Automobile Sim',
	'Baseball',
	'Base Building',
	'Based On A Novel',
	'Basketball',
	'Battle Royale',
	'Beat em up',
	'Beautiful',
	'Benchmark',
	'Bikes',
	'Blood',
	'BMX',
	'Board Game',
	'Boss Rush',
	'Bowling',
	'Boxing',
	'Building',
	'Bullet Hell',
	'Bullet Time',
	'Capitalism',
	'Card Battler',
	'Card Game',
	'Cartoon',
	'Cartoony',
	'Casual',
	'Cats',
	'Character Action Game',
	'Character Customization',
	'Chess',
	'Choices Matter',
	'Choose Your Own Adventure',
	'Cinematic',
	'City Builder',
	'Class Based',
	'Classic',
	'Clicker',
	'Coding',
	'Cold War',
	'Collectathon',
	'Colony Sim',
	'Colorful',
	'Combat',
	'Combat Racing',
	'Comedy',
	'Competitive',
	'Comic Book',
	'Conspiracy',
	'Controller',
	'Conversation',
	'Cooking',
	'Co-op Campaign',
	'Cozy',
	'Crafting',
	'Creature Collector',
	'Cricket',
	'Crime',
	'Crowdfunded',
	'CRPG',
	'Cult Classic',
	'Cute',
	'Cyberpunk',
	'Cycling',
	'Dark',
	'Dark Comedy',
	'Dark Fantasy',
	'Dating Sim',
	'Deckbuilding',
	'Demons',
	'Design & Illustration',
	'Destruction',
	'Detective',
	'Dragons',
	'Dungeon Crawler',
	'Dark Humor',
	'Difficult',
	'Diplomacy',
	'Dinosaurs',
	'Documentary',
	'Dog',
	'Drama',
	'Driving',
	'Dungeons & Dragons',
	'Dynamic Narration',
	'Dystopian',
	'Early Access',
	'Economy',
	'Education',
	'Electronic',
	'Electronic Music',
	'Emotional',
	'Epic',
	'Episodic',
	'Escape Room',
	'eSports',
	'Experience',
	'Experimental',
	'Exploration',
	'Faith',
	'Family Friendly',
	'Fantasy',
	'Farming',
	'Farming Sim',
	'Fast-Paced',
	'Feature Film',
	'Female Protagonist',
	'Fighting',
	'First-Person',
	'Fishing',
	'Flight',
	'FMV',
	'Football (American)',
	'Football (Soccer)',
	'Foreign',
	'FPS',
	'Free to Play',
	'Funny',
	'Futuristic',
	'Gambling',
	'Game Development',
	'GameMaker',
	'Games Workshop',
	'Gaming',
	'God Game',
	'Golf',
	'Gore',
	'Gothic',
	'Grand Strategy',
	'Great Soundtrack',
	'Grid-Based Movement',
	'Gun Customization',
	'Hacking',
	'Hack and Slash',
	'Hand-drawn',
	'Hardware',
	'Heist',
	'Hentai',
	'Hero Shooter',
	'Hex Grid',
	'Hidden Object',
	'Historical',
	'Hobby Sim',
	'Hockey',
	'Horror',
	'Horses',
	'Hunting',
	'Idler',
	'Illuminati',
	'Immersive',
	'Immersive Sim',
	'Indie',
	'Interactive Fiction',
	'Instrumental Music',
	'Intentionally Awkward Controls',
	'Investigation',
	'Inventory Management',
	'Isometric',

	'Jet',
	'Job Simulator',
	'JRPG',
	'Jump Scare',
	'Kickstarter',
	'LEGO',
	'Lemmings',
	'Level Editor',
	'LGBTQ+',
	'Life Sim',
	'Linear',
	'Local Co-Op',
	'Local Multiplayer',
	'Logic',
	'Loot',
	'Looter Shooter',
	'Lore-Rich',
	'Lovecraftian',
	'Magic',
	'Mahjong',
	'Male Protagonist',
	'Management',
	'Mars',
	'Martial Arts',
	'Massively Multiplayer',
	'Match 3',
	'Mature',
	'Mechs',
	'Medical Sim',
	'Medieval',
	'Memes',
	'Metroidvania',
	'Military',
	'Mini Golf',
	'Minigames',
	'Minimalist',
	'Mining',
	'MMORPG',
	'MOBA',
	'Mod',
	'Moddable',
	'Modern',
	'Motocross',
	'Motorbike',
	'Mouse only',
	'Movie',
	'Multiplayer',
	'Multiple Endings',
	'Music',
	'Music-Based Procedural Generation',
	'Musou',
	'Mystery',
	'Mystery Dungeon',
	'Mythology',
	'Narration',
	'Narrative',
	'Nature',
	'Naval',
	'Naval Combat',
	'Ninja',
	'Noir',
	'Nonlinear',
	'Nostalgia',
	'NSFW',
	'Nudity',
	'Offroad',
	'Old School',
	'Online Co-Op',
	'On-Rails Shooter',
	'Open World',
	'Open World Survival Craft',
	'Otome',
	'Outbreak Sim',
	'Parkour',
	'Parody',
	'Party',
	'Party-Based RPG',
	'Party Game',
	'Perma Death',
	'Philosophical',
	'Photo Editing',
	'Physics',
	'Pinball',
	'Pirates',
	'Pixel Graphics',
	'Platformer',
	'Point & Click',
	'Political',
	'Political Sim',
	'Politics',
	'Pool',
	'Post-Apocalyptic',
	'Precision Platformer',
	'Procedural Generation',
	'Programming',
	'Psychedelic',
	'Psychological',
	'Psychological Horror',
	'Puzzle',
	'Puzzle Platformer',
	'PvE',
	'PvP',
	'Quick-Time Events',
	'Racing',
	'Real-Time',
	'Real-Time with Pause',
	'Real-Time Tactics',
	'Realistic',
	'Reboot',
	'Relaxing',
	'Remake',
	'Replay Value',
	'Resource Management',
	'Retro',
	'Rhythm',
	'Robots',
	'Rock Music',
	'Roguelike',
	'Roguelike Deckbuilder',
	'Roguelite',
	'Roguevania',
	'Romance',
	'Rome',
	'RPG',
	'RPGMaker',
	'RTS',
	'Rugby',
	'Runner',
	'Sandbox',
	'Sailing',
	'Sci-fi',
	'Science',
	'Score Attack',
	'Sexual Content',
	'Sequel',
	'Shoot Em Up',
	'Shooter',
	'Shop Keeper',
	'Short',
	'Side Scroller',
	'Silent Protagonist',
	'Simulation',
	'Singleplayer',
	'Skateboarding',
	'Skating',
	'Skiing',
	'Sniper',
	'Snooker',
	'Snow',
	'Snowboarding',
	'Social Deduction',
	'Software',
	'Software Training',
	'Sokoban',
	'Solitaire',
	'Souls-like',
	'Soundtrack',
	'Space',
	'Space Sim',
	'Spaceships',
	'Spectacle fighter',
	'Spelling',
	'Split Screen',
	'Sports',
	'Stealth',
	'Steam Machine',
	'Steampunk',
	'Story Rich',
	'Strategy',
	'Strategy RPG',
	'Stylized',
	'Submarine',
	'Superhero',
	'Supernatural',
	'Surreal',
	'Survival',
	'Survival Horror',
	'Swordplay',
	'Tabletop',
	'Tactical',
	'Tactical RPG',
	'Tanks',
	'Team Based',
	'Tennis',
	'Text Based',
	'Third Person',
	'Third Person Shooter',
	'Thriller',
	'Tile Matching',
	'Time Attack',
	'Time Management',
	'Time Manipulation',
	'Time Travel',
	'Top-Down',
	'Top-Down Shooter',
	'Touch Friendly',
	'Tower Defense',
	'TrackIR',
	'Trading',
	'Trading Card Game',
	'Traditional Roguelike',
	'Trains',
	'Transhumanism',
	'Transportation',
	'Trivia',
	'Turn-Based',
	'Turn-Based Combat',
	'Turn-Based Strategy',
	'Turn-Based Tactics',
	'Tutorial',
	'Twin Stick Shooter',
	'Typing',
	'Underground',
	'Underwater',
	'Unforgiving',
	'Utilities',
	'Vampire',
	'Vehicular Combat',
	'Video Production',
	'Vikings',
	'Villain Protagonist',
	'Violent',
	'Visual Novel',
	'Voice Control',
	'Voiced',
	'Volleyball',
	'Voxel',
	'VR',
	'Walking Simulator',
	'War',
	'Wargame',
	'Warhammer 40K',
	'Web Publishing',
	'Well-Written',
	'Werewolves',
	'Western',
	'Wholesome',
	'Word Game',
	'World War I',
	'World War II',
	'Wrestling',
	'Zombies',
	'1980s',
	'2D',
	'1990s',
	'2D Fighter',
	'2D Platformer',
	'2.5D',
	'3D',
	'3D Platformer',
	'360 Video',
	'4 Player Local',
	'4X',
	'8-bit Music',
	'6DOF',
	'3D Fighter',
	'3D Vision',
]


export const adultContentTags = [
	'Anal Sex',
	'Ahegao',
	'Bdsm',
	'Bestiality',
	'Big Ass',
	'Big Tits',
	'Blackmail',
	'Bukkake',
	'Cheating',
	'Corruption',
	'Creampie',
	'Dilf',
	'Drugs',
	'Exhibitionism',
	'Female domination',
	'Footjob',
	'Furry',
	'Futa/Trans',
	'Gay',
	'Group sex',
	'Groping',
	'Handjob',
	'Harem',
	'Humiliation',
	'Incest',
	'Internal view',
	'Interracial',
	'Lactation',
	'Lesbian',
	'Loli',
	'Male Domination',
	'Masturbation',
	'Milf',
	'Multiple Penetration',
	'Necrophilia',
	'Netorare',
	'Oral Sex',
	'Pregnancy',
	'Prostitution',
	'Rape',
	'Scat',
	'Sex Toys',
	'Sexual Harassment',
	'Shota',
	'Sissification',
	'Slave',
	'Sleep Sex',
	'Spanking',
	'Stripping',
	'Swinging',
	'Tentacles',
	'Teasing',
	'Titfuck',
	'Transformation',
	'Trap',
	'Urination',
	'Vaginal sex',
	'Virgin',
	'Vore',
	'Voyeurism',
]